import type { Report } from "@/types/analytics";

export function exportReportsCsv(reports: Report[]) {
  const headers = ["Name", "Project", "Category", "Source", "Visitors", "Revenue", "Conversion", "Created", "Status"];
  const rows = reports.map((report) => [
    report.name,
    report.project,
    report.category,
    report.source,
    report.visitors,
    report.revenue,
    `${report.conversion}%`,
    report.createdAt,
    report.status
  ]);

  const csv = [headers, ...rows]
    .map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(","))
    .join("\n");

  triggerDownload(new Blob([csv], { type: "text/csv;charset=utf-8;" }), `devpulse-reports-${today()}.csv`);
}

export function exportReportsPdf(reports: Report[], title = "DevPulse Analytics Report") {
  const rows = reports
    .map(
      (r) =>
        `<tr>
          <td>${r.name}</td>
          <td>${r.project}</td>
          <td>${r.category}</td>
          <td>${r.source}</td>
          <td>${r.visitors.toLocaleString()}</td>
          <td>$${r.revenue.toLocaleString()}</td>
          <td>${r.conversion}%</td>
          <td>${r.createdAt}</td>
          <td>${r.status}</td>
        </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 32px; color: #0f172a; }
    h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
    p { font-size: 13px; color: #64748b; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { background: #f1f5f9; padding: 8px 12px; text-align: left; font-weight: 600; border-bottom: 1px solid #e2e8f0; }
    td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; }
    tr:last-child td { border-bottom: none; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p>Generated by DevPulse Cloud · ${new Date().toLocaleString()}</p>
  <table>
    <thead>
      <tr>
        <th>Report</th><th>Project</th><th>Category</th><th>Source</th>
        <th>Visitors</th><th>Revenue</th><th>Conversion</th><th>Date</th><th>Status</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => {
    win.print();
  }, 400);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

function today() {
  return new Date().toISOString().slice(0, 10);
}
